{
 "title": "Speed Test",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "ISP - Speedtest - Download",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "speedtest_download", "legendFormat": "download" }
   ]
  },
  {
   "title": "ISP - Speedtest - Upload",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "speedtest_upload", "legendFormat": "upload" }
   ]
  },
  {
   "title": "ISP - Speedtest - Ping",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "speedtest_ping", "legendFormat": "ping" }
   ]
  },
  {
   "title": "ISP - Speedtest - Download",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_download", "legendFormat": "download" }
   ]
  },
  {
   "title": "ISP - Speedtest - Upload",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_upload", "legendFormat": "upload" }
   ]
  },
  {
   "title": "ISP - Speedtest - Ping",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_ping", "legendFormat": "ping" }
   ]
  }
 ]
}